title: Herianto
logo: /assets/img/foto_non_formal.jpg
description: I have significant experience handling experimental data for laboratory exercises throughout my college tenure.
theme: jekyll-theme-minimal
