title: Herianto
logo: /assets/img/foto_non_formal.jpg
description: As an aspiring data scientist, I possess significant experience handling experimental data for laboratory exercises throughout
my college tenure. I am proficient in both manual and automated data collection methods, utilizing programming languages
like Python, Matlab, and C/C++. My latest endeavor involved analyzing automobile datasets to predict car prices using Python
within the Jupyter Notebook environment.
theme: jekyll-theme-minimal
